### PR TITLE
fix: make more spec-compliant

### LINKED ISSUE #1: Make spec-compliant
Please make this module spec-compliant :) An example where it is not that I noticed right away is that this module considers any request with an `Origin` request header to be a CORS request--this is actually not the indicator of what is or isn't a CORS request. You can find more within the spec.

The biggest failure right now is this module doesn't correctly handle pre flight requests, as it makes a mistakes in the processing of section 6.2 (http://www.w3.org/TR/cors/#resource-preflight-requests), step 3:

> If there is no Access-Control-Request-Method header or if parsing failed, do not set any additional headers and terminate this set of steps. The request is outside the scope of this specification.

If I send an `OPTIONS` request with an `Origin` request header and no ` Access-Control-Request-Method` request header, this module still adds CORS response headers.

You can find the spec here: http://www.w3.org/TR/cors/

### PR DESCRIPTION
**Pull request by fengmk2**
Fixes #1

### CODE REVIEW

**Comment by fengmk2** [comment]
- If request missing `Origin` header, ignore it
- If `OPTIONS` request missing `Access-Control-Request-Method` header, ignore it
- `Access-Control-Max-Age`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers` only set on Preflight(`OPTIONS`) Request.
- `Access-Control-Expose-Headers` only set on Simple Request.

**Comment by fengmk2** [comment]
@dougwilson any suggestion?

**Comment by dougwilson** [comment]
Sorry, sometimes the emails get lost in my box :) LGTM

**Comment by fengmk2** [comment]
release 1.0.1

**Pull request merged**
