### PR TITLE
add PATCH to default methods

### PR DESCRIPTION
**Pull request by defunctzombie**

### CODE REVIEW

**Comment by defunctzombie** [comment]
Let me know if you think this warrants tests.

**Comment by fengmk2** [comment]
+1

I will fix the tests before merge.

**Comment by fengmk2** [comment]
landed 9b641247cbd5c772a9afcdf5c9e8b23926242300

**Comment by fengmk2** [comment]
1.3.0 released

**Comment by fengmk2** [comment]
Also pick to v2.x branch 7f0a28de8d8dd033132b314f0f0b288e6f1e1934

**Pull request closed without merging**
