### PR TITLE
Fix: bug between credentials and origin

### PR DESCRIPTION
**Pull request by TyrealHu**
## Checklist
cannot set Access-Control-Allow-Origin to *, when Access-Control-Allow-Credentials is true
- [x] I have ensured my pull request is not behind the main or master branch of the original repository.
- [x] I have rebased all commits where necessary so that reviewing this pull request can be done without having to merge it first.
- [x] I have written a commit message that passes commitlint linting.
- [x] I have ensured that my code changes pass linting tests.
- [x] I have ensured that my code changes pass unit tests.
- [x] I have described my pull request and the reasons for code changes along with context if necessary.

### CODE REVIEW

**Comment by TyrealHu** [comment]
cannot set Access-Control-Allow-Origin to *, when Access-Control-Allow-Credentials is true

**Comment by fengmk2** [comment]
@TyrealHu Can you add a test for this change?

**Comment by TyrealHu** [comment]
@fengmk2 Of course,i will add a test later.btw i think you should reconfigure the Node.js CI🐛

**Comment by TyrealHu** [comment]
@fengmk2 i have already added a unit test for this feature, thx❤️

**Comment by fengmk2** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
image

LGTM

**Review by fengmk2 — APPROVED** [review]

**Comment by fengmk2** [comment]
3.4.1

**Pull request merged**
