### PR TITLE
Vary: Origin

### PR DESCRIPTION
**Pull request by lishengzxc**

### CODE REVIEW

**Comment by fengmk2** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary

**Comment by fengmk2** [comment]
Please add the tests for these changes

**Comment by lishengzxc** [comment]
@fengmk2 done~

**Comment by fengmk2** [comment]
2.2.1

**Comment by fengmk2** [comment]
@lishengzxc can you patch this change into master?

**Comment by lishengzxc** [comment]
@fengmk2 only add `Vary: Origin` for master rather than merge v2.x into master?

**Comment by fengmk2** [comment]
@lishengzxc yes.

**Pull request merged**
