### PR TITLE
Koa2

### PR DESCRIPTION
**Pull request by omsmith**

### CODE REVIEW

**Comment by tejasmanohar** [comment]
+1 from me. Tested and works fine! // cc @fengmk2

**Comment by menems** [comment]
+1

**Comment by fengmk2** [comment]
Wait for koajs/koa#533 voting result.

**Comment by rrdelaney** [comment]
Can this be merged as a v2 branch and published to npm as such?

**Comment by fengmk2** [comment]
I will merge this into v2.x branch.

**Comment by tejasmanohar** [comment]
push to @next tag on npm

**Comment by fengmk2** [comment]
@tejasmanohar sure, working on this.

**Comment by fengmk2** [comment]
Landed d46b611b5b71786c7aefc0b830c911087a4e5b27

**Comment by fengmk2** [comment]
```bash
npm dist-tag ls
latest: 1.0.1
next: 2.0.0
```

**Pull request closed without merging**
